import { Roboto_Condensed } from 'next/font/google';
import { Suspense } from 'react';

import ReduxProvider from '@/lib/Provider';

import Header from '@/compositions/Header';
import Footer from '@/compositions/Footer';

import './styles/globals.css';

const roboto = Roboto_Condensed({ subsets: ['latin'] });

export const metadata = {
  title: 'Dental Elida Groupe',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <ReduxProvider>
          <Header />
          <Suspense>
            <main>{children}</main>
          </Suspense>

          <Footer />
        </ReduxProvider>
      </body>
    </html>
  );
}
