import { Suspense } from 'react';
import './styles/globals.css';

import { Roboto_Condensed } from 'next/font/google';
import { AntdRegistry } from '@ant-design/nextjs-registry';

import ReduxProvider from '@/lib/Provider';

import Header from '@/compositions/Header';
import Footer from '@/compositions/Footer';
import MainPage from '@/compositions/MainPage';

const roboto = Roboto_Condensed({ subsets: ['latin'] });

export const metadata = {
  title: 'Dental Elida Groupe',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <AntdRegistry>
          <ReduxProvider>
            <Header />

            <main>
              <MainPage>{children}</MainPage>
            </main>

            <Footer />
          </ReduxProvider>
        </AntdRegistry>
      </body>
    </html>
  );
}
