import { Suspense } from 'react';
import './styles/globals.css';

import { Roboto_Condensed } from 'next/font/google';
import { AntdRegistry } from '@ant-design/nextjs-registry';

import ReduxProvider from '@/lib/Provider';

import Header from '@/compositions/Header';
import Footer from '@/compositions/Footer';
import MainPage from '@/compositions/MainPage';

const roboto = Roboto_Condensed({ subsets: ['latin'] });

export const metadata = {
  title: 'Dental Elida Groupe',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <AntdRegistry>
          <ReduxProvider>
            <Header />
            <Suspense
              fallback={
                <p
                  style={{
                    width: '100wh',
                    height: '100vh',
                    display: 'flex',
                    alignItems: 'center',
                    justifyContent: 'center',
                    fontSize: '3.2rem',
                    background: 'red',
                  }}
                >
                  Loading Suspense ...
                </p>
              }
            >
              <main>
                <MainPage>{children}</MainPage>
              </main>
            </Suspense>

            <Footer />
          </ReduxProvider>
        </AntdRegistry>
      </body>
    </html>
  );
}
